name: CI/CD Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:  Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: abirzishan/ci_cd_practice:latest  # Update with your actual Docker Hub username and repository name
  
  deploys:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to VM 
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull abirzishan/ci_cd_practice:latest
            docker stop ci_cd_practice || true
            docker rm ci_cd_practice || true
            docker run -d -p 80:80 --name ci_cd_practice abirzishan/ci_cd_practice:latest
